server:
  port: 8088
spring:
  application:
    name: notification-service
  artemis:
    mode: native
    broker-url: tcp://localhost:61616
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
