server:
  port: 8091

spring:
  application:
    name: pos-terminal-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.payment: DEBUG
    com.payment.pos: DEBUG
    com.payment.security: DEBUG
    com.payment.iso8583: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"